[workspace]
resolver = "2"


members = ["apps/server", "apps/simulator", "crates/core", "crates/transport"]

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tower-http = { version = "0.7", features = ["trace"] }
tower = { version = "0.5", features = ["util"] }
